name = Homepage
description = A layout with off canvas responsive navigation pattern.
preview = preview.png
template = homepage-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[content]        = Content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/homepage/homepage.layout.css

; Scripts
scripts[] = layouts/homepage/assets/off-canvas.js
