name = Chapters
description = A layout for foodbytes chapters with off canvas responsive navigation pattern.
preview = preview.png
template = chapters-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/chapters/chapters.layout.css
stylesheets[all][] = css/layouts/chapters/chapters.no-query.layout.css

; Scripts
scripts[] = layouts/chapters/assets/off-canvas.js
scripts[] = layouts/chapters/assets/jquery.collapse.js
scripts[] = layouts/chapters/assets/jquery.collapse_storage.js
scripts[] = layouts/chapters/assets/jquery.collapse_cookie_storage.js
 