name = Chapter child
description = A layout for foodbytes chapter subpages with off canvas responsive navigation pattern.
preview = preview.png
template = chapterchild-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/chapterchild/chapterchild.layout.css
stylesheets[all][] = css/layouts/chapterchild/chapterchild.no-query.layout.css

; Scripts
scripts[] = layouts/chapterchild/assets/off-canvas.js
scripts[] = layouts/chapterchild/assets/pin.js
scripts[] = layouts/chapterchild/assets/jquery.scrollorama.js